spring:
  application:
    name: techeng
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/techeng
    username: ${DB_USERNAME:techeng}
    password: ${DB_PASSWORD:techeng_dev}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
